// <auto-generated />
using FLAMOM_SeniorProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FLAMOM_SeniorProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FLAMOM_SeniorProject.Data.HeardAbout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HeardAboutHow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitInfoId");

                    b.ToTable("HeardAbouts");
                });

            modelBuilder.Entity("FLAMOM_SeniorProject.Data.ReasonForVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitInfoId");

                    b.ToTable("ReasonsForVisit");
                });

            modelBuilder.Entity("FLAMOM_SeniorProject.Data.VisitInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AttendBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthOfPain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MouthPain")
                        .HasColumnType("bit");

                    b.Property<string>("OverallHealth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeToTravel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitInformations");
                });

            modelBuilder.Entity("FLAMOM_SeniorProject.Data.HeardAbout", b =>
                {
                    b.HasOne("FLAMOM_SeniorProject.Data.VisitInformation", "VisitInfo")
                        .WithMany("HeardAbouts")
                        .HasForeignKey("VisitInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitInfo");
                });

            modelBuilder.Entity("FLAMOM_SeniorProject.Data.ReasonForVisit", b =>
                {
                    b.HasOne("FLAMOM_SeniorProject.Data.VisitInformation", "VisitInfo")
                        .WithMany("ReasonsForVisit")
                        .HasForeignKey("VisitInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitInfo");
                });

            modelBuilder.Entity("FLAMOM_SeniorProject.Data.VisitInformation", b =>
                {
                    b.Navigation("HeardAbouts");

                    b.Navigation("ReasonsForVisit");
                });
#pragma warning restore 612, 618
        }
    }
}
